/* AUBS build stamp — writes build-info.js from VERSION + the short git hash + build time,
   so the on-device footer visibly changes on EVERY deploy (no more guessing whether the
   phone is running fresh code from a static "trust-os-1 · cp0-spine-1.3.1" marker).

   Run automatically by .github/workflows/pages.yml at deploy time. Run manually before a
   hand deploy with: node tools/stamp-build.cjs

   The committed build-info.js is a "dev" fallback so file:// and un-stamped branch deploys
   still load; the deploy workflow overwrites it in the published artifact only. */
"use strict";
const fs = require("fs");
const path = require("path");
const { execSync } = require("child_process");
const ROOT = path.join(__dirname, "..");

function sh(cmd) { try { return execSync(cmd, { cwd: ROOT }).toString().trim(); } catch (e) { return ""; } }

const version = (function () {
  try { return fs.readFileSync(path.join(ROOT, "VERSION"), "utf8").trim(); } catch (e) { return "0.0.0"; }
})();
const commit = process.env.GITHUB_SHA ? process.env.GITHUB_SHA.slice(0, 7) : (sh("git rev-parse --short HEAD") || "unknown");
const builtAt = new Date().toISOString();

const out = "/* AUTO-GENERATED by tools/stamp-build.cjs — do not edit by hand. */\n" +
  "(typeof window!==\"undefined\"?window:globalThis).AUBS_BUILD = " +
  JSON.stringify({ version: version, commit: commit, built_at: builtAt }) + ";\n";

fs.writeFileSync(path.join(ROOT, "build-info.js"), out);
console.log("stamped build-info.js →", version, commit, builtAt);
